//! Coefficient-domain abstraction: the finite rings `Z/2^k` for the research
//! widths k in {2, 4, 8, 16, 64}, per spec §16.1.
//!
//! The [`Word`] trait exposes exactly the operations the specification uses and
//! nothing more. Concrete widths are generated by the [`impl_word!`] macro as
//! distinct newtypes that **do not** implement `core::ops::{Add, Mul, ...}`, so
//! ordinary (accidentally overflowing) arithmetic simply does not compile — the
//! only arithmetic available is the explicit wrapping API below.
//!
//! Every externally constructed value is masked into the canonical `k`-bit range
//! by [`Word::from_u64`]; every operation returns a canonical value.

/// A coefficient of the octonion algebra: an element of `Z/2^BITS`.
///
/// Implementors store a canonical representative in `[0, 2^BITS)`. No
/// floating-point, no OS entropy, no platform-dependent behavior.
pub trait Word: Copy + Clone + PartialEq + Eq + core::fmt::Debug + core::hash::Hash {
    /// Bit width `k`; the ring is `Z/2^BITS`.
    const BITS: u32;
    /// Additive identity `0`.
    const ZERO: Self;
    /// Multiplicative identity `1`.
    const ONE: Self;

    /// Construct from a `u64`, masking to the canonical `BITS`-bit range.
    fn from_u64(v: u64) -> Self;
    /// Canonical value in `[0, 2^BITS)` as a `u64`.
    fn to_u64(self) -> u64;

    /// Wrapping addition in `Z/2^BITS`.
    fn wadd(self, other: Self) -> Self;
    /// Wrapping subtraction in `Z/2^BITS`.
    fn wsub(self, other: Self) -> Self;
    /// Wrapping multiplication in `Z/2^BITS`.
    fn wmul(self, other: Self) -> Self;
    /// Wrapping negation (two's complement) in `Z/2^BITS`.
    fn wneg(self) -> Self;
    /// Bitwise XOR of the canonical `BITS`-bit representatives.
    fn xor(self, other: Self) -> Self;
    /// Left bit-rotation **within `BITS` bits** by `n mod BITS` (spec `ROT_λ`).
    fn rotl(self, n: u32) -> Self;

    /// 2-adic valuation of the representative, capped at `BITS`
    /// (so `v(0) == BITS`). Used by the modular linear-algebra tooling.
    fn valuation(self) -> u32 {
        let v = self.to_u64();
        if v == 0
        {
            Self::BITS
        }
        else
        {
            v.trailing_zeros().min(Self::BITS)
        }
    }

    /// `true` iff this is a unit of `Z/2^BITS` (i.e. odd).
    fn is_unit(self) -> bool {
        self.to_u64() & 1 == 1
    }

    /// Multiplicative inverse if this is a unit (odd), else `None`.
    /// Newton iteration for the inverse of an odd number mod `2^BITS`.
    fn inv(self) -> Option<Self> {
        if !self.is_unit()
        {
            return None;
        }
        // x_{n+1} = x_n * (2 - a * x_n) doubles correct bits each step.
        let a = self;
        let mut x = Self::ONE;
        // ceil(log2(BITS)) iterations suffice; 6 covers BITS up to 64.
        for _ in 0..6
        {
            let two = Self::ONE.wadd(Self::ONE);
            x = x.wmul(two.wsub(a.wmul(x)));
        }
        Some(x)
    }
}

macro_rules! impl_word {
    ($name:ident, $bits:expr) => {
        #[doc = concat!("Coefficient in `Z/2^", stringify!($bits), "`.")]
        #[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
        pub struct $name(u64);

        impl $name {
            const MASK: u64 = if $bits >= 64
            {
                u64::MAX
            }
            else
            {
                (1u64 << $bits) - 1
            };
        }

        impl Word for $name {
            const BITS: u32 = $bits;
            const ZERO: Self = $name(0);
            const ONE: Self = $name(
                1 & (if $bits >= 64
                {
                    u64::MAX
                }
                else
                {
                    (1u64 << $bits) - 1
                }),
            );

            #[inline]
            fn from_u64(v: u64) -> Self {
                $name(v & Self::MASK)
            }
            #[inline]
            fn to_u64(self) -> u64 {
                self.0 & Self::MASK
            }
            #[inline]
            fn wadd(self, o: Self) -> Self {
                $name(self.0.wrapping_add(o.0) & Self::MASK)
            }
            #[inline]
            fn wsub(self, o: Self) -> Self {
                $name(self.0.wrapping_sub(o.0) & Self::MASK)
            }
            #[inline]
            fn wmul(self, o: Self) -> Self {
                $name(self.0.wrapping_mul(o.0) & Self::MASK)
            }
            #[inline]
            fn wneg(self) -> Self {
                $name(0u64.wrapping_sub(self.0) & Self::MASK)
            }
            #[inline]
            fn xor(self, o: Self) -> Self {
                $name((self.0 ^ o.0) & Self::MASK)
            }
            #[inline]
            fn rotl(self, n: u32) -> Self {
                let b = $bits as u32;
                let r = n % b;
                if r == 0
                {
                    return $name(self.0 & Self::MASK);
                }
                let v = self.0 & Self::MASK;
                $name(((v << r) | (v >> (b - r))) & Self::MASK)
            }
        }
    };
}

impl_word!(W2, 2);
impl_word!(W4, 4);
impl_word!(W8, 8);
impl_word!(W16, 16);
impl_word!(W64, 64);

/// The five research coefficient widths, tagged for CLI/report metadata.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum WidthTag {
    /// `Z/2^2` — spec variant `NANO-2`.
    Nano2,
    /// `Z/2^4` — spec variant `NANO-4`.
    Nano4,
    /// `Z/2^8` — spec variant `MINI-8`.
    Mini8,
    /// `Z/2^16` — spec variant `MINI-16`.
    Mini16,
    /// `Z/2^64` — full v0.1 coefficient domain.
    Full64,
}

impl WidthTag {
    /// Bit width `k`.
    pub fn bits(self) -> u32 {
        match self
        {
            WidthTag::Nano2 => 2,
            WidthTag::Nano4 => 4,
            WidthTag::Mini8 => 8,
            WidthTag::Mini16 => 16,
            WidthTag::Full64 => 64,
        }
    }
    /// Spec variant name.
    pub fn variant_name(self) -> &'static str {
        match self
        {
            WidthTag::Nano2 => "NANO-2",
            WidthTag::Nano4 => "NANO-4",
            WidthTag::Mini8 => "MINI-8",
            WidthTag::Mini16 => "MINI-16",
            WidthTag::Full64 => "FULL-64",
        }
    }
    /// Parse from a CLI token like `nano2`, `mini8`, `full64`.
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str()
        {
            "nano2" | "nano-2" | "k2" => Some(WidthTag::Nano2),
            "nano4" | "nano-4" | "k4" => Some(WidthTag::Nano4),
            "mini8" | "mini-8" | "k8" => Some(WidthTag::Mini8),
            "mini16" | "mini-16" | "k16" => Some(WidthTag::Mini16),
            "full64" | "full-64" | "k64" => Some(WidthTag::Full64),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn masking_is_canonical() {
        assert_eq!(W2::from_u64(0b1011).to_u64(), 0b11);
        assert_eq!(W4::from_u64(0xFF).to_u64(), 0xF);
        assert_eq!(W8::from_u64(0x1FF).to_u64(), 0xFF);
        assert_eq!(W64::from_u64(u64::MAX).to_u64(), u64::MAX);
    }

    #[test]
    fn wrapping_ops() {
        // Z/2^4: 15 + 1 = 0
        assert_eq!(W4::from_u64(15).wadd(W4::ONE).to_u64(), 0);
        // Z/2^4: 0 - 1 = 15
        assert_eq!(W4::ZERO.wsub(W4::ONE).to_u64(), 15);
        // Z/2^4: 4 * 4 = 16 = 0
        assert_eq!(W4::from_u64(4).wmul(W4::from_u64(4)).to_u64(), 0);
        // negation
        assert_eq!(W8::from_u64(1).wneg().to_u64(), 255);
    }

    #[test]
    fn rotate_within_width() {
        // W2: rotate 0b10 left by 1 -> 0b01
        assert_eq!(W2::from_u64(0b10).rotl(1).to_u64(), 0b01);
        // W4: rotate 0b1000 left by 1 -> 0b0001
        assert_eq!(W4::from_u64(0b1000).rotl(1).to_u64(), 0b0001);
        // rotl by BITS is identity
        assert_eq!(W8::from_u64(0xA5).rotl(8).to_u64(), 0xA5);
        assert_eq!(
            W64::from_u64(0x0123456789abcdef).rotl(64).to_u64(),
            0x0123456789abcdef
        );
    }

    #[test]
    fn units_and_inverses() {
        // odd numbers are units; a * a^{-1} == 1
        for w in [
            W4::from_u64(1),
            W4::from_u64(3),
            W4::from_u64(7),
            W4::from_u64(15),
        ]
        {
            let inv = w.inv().expect("odd is a unit");
            assert_eq!(w.wmul(inv).to_u64(), 1);
        }
        // even numbers are non-units
        assert!(W8::from_u64(2).inv().is_none());
        assert!(W8::from_u64(0).inv().is_none());
        // W64 inverse round-trips
        let a = W64::from_u64(0x9e3779b97f4a7c15);
        assert_eq!(a.wmul(a.inv().unwrap()).to_u64(), 1);
    }

    #[test]
    fn valuation_capped() {
        assert_eq!(W8::from_u64(0).valuation(), 8);
        assert_eq!(W8::from_u64(1).valuation(), 0);
        assert_eq!(W8::from_u64(0b100).valuation(), 2);
        assert_eq!(W8::from_u64(0b1000_0000).valuation(), 7);
    }
}
