//! Orthogonal projector generated by an SRCC closure.

use crate::{LinearMap16, SrccClosure, SrccClosureError, SrccConfig, Vector16, apply_linear_map};

#[derive(Clone, Debug, PartialEq)]
pub struct SrccProjector {
    closure: SrccClosure,
    transform: LinearMap16,
}

impl SrccProjector {
    pub fn build(
        seeds: &[Vector16],
        transports: &[LinearMap16],
        config: SrccConfig,
    ) -> Result<Self, SrccClosureError> {
        let closure = SrccClosure::build(seeds, transports, config)?;

        Ok(Self::from_closure(closure))
    }

    #[must_use]
    pub fn from_closure(closure: SrccClosure) -> Self {
        let transform = core::array::from_fn(|row| {
            core::array::from_fn(|column| {
                let identity = if row == column { 1.0 } else { 0.0 };

                closure.basis().iter().fold(identity, |value, direction| {
                    value - direction[row] * direction[column]
                })
            })
        });

        Self { closure, transform }
    }

    #[must_use]
    pub fn apply(&self, input: &Vector16) -> Vector16 {
        apply_linear_map(&self.transform, input)
    }

    #[must_use]
    pub const fn transform(&self) -> &LinearMap16 {
        &self.transform
    }

    #[must_use]
    pub const fn closure(&self) -> &SrccClosure {
        &self.closure
    }

    #[must_use]
    pub fn rejected_dimension(&self) -> usize {
        self.closure.dimension()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{SRCC_DIMENSION, basis_vector, squared_norm};

    fn transport(source: usize, target: usize, coefficient: f64) -> LinearMap16 {
        let mut map = [[0.0; SRCC_DIMENSION]; SRCC_DIMENSION];

        map[target][source] = coefficient;
        map
    }

    fn squared_distance(left: &Vector16, right: &Vector16) -> f64 {
        left.iter().zip(right).fold(0.0, |sum, (a, b)| {
            let difference = a - b;
            sum + difference * difference
        })
    }

    #[test]
    fn projector_rejects_consensus_closure() {
        let seeds = [basis_vector(1).unwrap()];
        let transports = [
            transport(1, 2, 1.0),
            transport(1, 2, -2.0),
            transport(1, 3, 1.0),
        ];

        let projector = SrccProjector::build(&seeds, &transports, SrccConfig::default()).unwrap();

        assert_eq!(projector.rejected_dimension(), 2);

        assert!(squared_norm(&projector.apply(&basis_vector(1).unwrap())) < 1.0e-24);

        assert!(squared_norm(&projector.apply(&basis_vector(2).unwrap())) < 1.0e-24);

        let preserved = basis_vector(3).unwrap();

        assert_eq!(projector.apply(&preserved), preserved);
    }

    #[test]
    fn projection_is_idempotent() {
        let seeds = [basis_vector(2).unwrap(), basis_vector(5).unwrap()];

        let transports = [transport(2, 7, 1.0), transport(2, 7, -1.0)];

        let projector = SrccProjector::build(&seeds, &transports, SrccConfig::default()).unwrap();

        let input: Vector16 = core::array::from_fn(|index| index as f64 - 6.0);

        let once = projector.apply(&input);
        let twice = projector.apply(&once);

        assert!(squared_distance(&once, &twice) < 1.0e-24);
    }

    #[test]
    fn transform_is_symmetric() {
        let seeds = [basis_vector(4).unwrap()];
        let transports = [transport(4, 6, 1.0), transport(4, 6, -1.0)];

        let projector = SrccProjector::build(&seeds, &transports, SrccConfig::default()).unwrap();

        for row in 0..SRCC_DIMENSION
        {
            for column in 0..SRCC_DIMENSION
            {
                assert!(
                    (projector.transform()[row][column] - projector.transform()[column][row]).abs()
                        < 1.0e-15
                );
            }
        }
    }
}
