//! Validation of the Rust ITD port against reference (numpy) oracle values.
//!
//! The fixtures in `support/oracle_data.rs` were generated by running the
//! original ITD V29 engine and operators. Every value below is checked to a
//! tight tolerance; the analytic sanity checks (irrotational field ⇒ zero
//! intensity, rigid rotation ⇒ constant vorticity) are covered in the unit
//! tests inside the crate.

// Auto-generated numeric fixtures: some literals coincide with math constants
// (e.g. 1/√2), which is not a readability problem in generated data.
#[allow(dead_code, clippy::approx_constant)]
mod oracle_data {
    include!("support/oracle_data.rs");
}

use oracle_data as od;
use scirust_itd::covariance::{
    galilean_source_coordinates, inverse_scale_coordinates, scale_geometry, scale_length,
    translating_frame_source_coordinates,
};
use scirust_itd::material::{
    AdvectionSource, material_vorticity_interval, simulate_canonical_material,
    simulate_material_deformation_with_advection,
};
use scirust_itd::multiscale::{MultiscaleReference, derive_multiscale_profile};
use scirust_itd::operators::{bounded, gradient, spatial_mean, vorticity};
use scirust_itd::scenarios::curvature_field;
use scirust_itd::signature::{StructuralWeights, structural_metrics};
use scirust_itd::transforms::{BilinearTransformPlan, Orthogonal2, transform_coordinates};
use scirust_itd::{
    BoundaryMode, Config, Field2, Geometry, Interpolation, Scenario, SimConfig, Trajectory,
    simulate_canonical_transport, transport_previous_vorticity,
};

const REL: f64 = 1e-9;
const ABS: f64 = 1e-11;

fn is_close(a: f64, b: f64) -> bool {
    (a - b).abs() <= ABS + REL * a.abs().max(b.abs())
}

#[track_caller]
fn assert_close(a: f64, b: f64, ctx: &str) {
    assert!(
        is_close(a, b),
        "{ctx}: got {a:.17e}, want {b:.17e}, diff {:.3e}",
        (a - b).abs()
    );
}

#[track_caller]
fn assert_slice_close(got: &[f64], want: &[f64], ctx: &str) {
    assert_eq!(got.len(), want.len(), "{ctx}: length mismatch");
    for (k, (&g, &w)) in got.iter().zip(want.iter()).enumerate()
    {
        assert_close(g, w, &format!("{ctx}[{k}]"));
    }
}

fn field(flat: &[f64]) -> Field2 {
    Field2::from_vec(od::NY, od::NX, flat.to_vec()).unwrap()
}

fn uniform() -> Geometry {
    Geometry::uniform(od::DX, od::DY).unwrap()
}

fn rectilinear() -> Geometry {
    Geometry::rectilinear(od::X_COORDS.to_vec(), od::Y_COORDS.to_vec()).unwrap()
}

// --- operators -----------------------------------------------------------

#[test]
fn gradient_uniform_finite() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &uniform(), BoundaryMode::Finite).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_UF_GY, "grad_uf_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_UF_GX, "grad_uf_gx");
}

#[test]
fn gradient_uniform_periodic() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &uniform(), BoundaryMode::Periodic).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_UP_GY, "grad_up_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_UP_GX, "grad_up_gx");
}

#[test]
fn gradient_rectilinear_finite() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &rectilinear(), BoundaryMode::Finite).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_RECT_GY, "grad_rect_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_RECT_GX, "grad_rect_gx");
}

#[test]
fn vorticity_uniform_finite() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &uniform(), BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UF, "vort_uf");
}

#[test]
fn vorticity_uniform_finite_isotropic() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let geom = Geometry::isotropic(od::DX).unwrap();
    let w = vorticity(&vx, &vy, &geom, BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UF_ISO, "vort_uf_iso");
}

#[test]
fn vorticity_uniform_periodic() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &uniform(), BoundaryMode::Periodic).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UP, "vort_up");
}

#[test]
fn vorticity_rectilinear_finite() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &rectilinear(), BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_RECT, "vort_rect");
}

#[test]
fn spatial_mean_matches() {
    let f = field(od::FIELD_A);
    assert_close(
        spatial_mean(&f, &uniform(), BoundaryMode::Finite).unwrap(),
        od::MEAN_UF,
        "mean_uf",
    );
    assert_close(
        spatial_mean(&f, &uniform(), BoundaryMode::Periodic).unwrap(),
        od::MEAN_UP,
        "mean_up",
    );
    assert_close(
        spatial_mean(&f, &rectilinear(), BoundaryMode::Finite).unwrap(),
        od::MEAN_RECT,
        "mean_rect",
    );
}

#[test]
fn bounded_matches() {
    for (&x, &want) in od::BOUNDED_IN.iter().zip(od::BOUNDED_OUT.iter())
    {
        assert_close(bounded(x), want, "bounded");
    }
}

#[test]
fn structural_metrics_matches() {
    let omega = field(od::FIELD_A);
    let prev = field(od::FIELD_B);
    let m = structural_metrics(
        &omega,
        &uniform(),
        Some(&prev),
        Some(od::SM_DT),
        od::SM_LEN,
        StructuralWeights::default(),
        BoundaryMode::Finite,
    )
    .unwrap();
    assert_close(m.heterogeneity, od::SM_HETEROGENEITY, "sm_het");
    assert_close(m.localization, od::SM_LOCALIZATION, "sm_loc");
    assert_close(m.roughness, od::SM_ROUGHNESS, "sm_rough");
    assert_close(m.sign_mixing, od::SM_SIGN_MIXING, "sm_sign");
    assert_close(
        m.temporal_deformation,
        od::SM_TEMPORAL_DEFORMATION,
        "sm_tdef",
    );
    assert_close(m.structure_score, od::SM_STRUCTURE_SCORE, "sm_score");
}

// --- scenarios -----------------------------------------------------------

struct ScenarioOracle {
    scenario: Scenario,
    intensity: f64,
    structure: f64,
    coupled: f64,
    components: [f64; 5],
}

fn check_scenarios(config: &Config, cases: &[ScenarioOracle], tag: &str) {
    let sim = SimConfig::default();
    for case in cases
    {
        let r = scirust_itd::simulate_canonical(case.scenario, config, &sim).unwrap();
        let ctx = format!("{tag}/{}", case.scenario.name());
        assert_close(
            r.intensity_index,
            case.intensity,
            &format!("{ctx}/intensity"),
        );
        assert_close(
            r.structure_index,
            case.structure,
            &format!("{ctx}/structure"),
        );
        assert_close(r.coupled_index, case.coupled, &format!("{ctx}/coupled"));
        assert_close(
            r.component_indices[0],
            case.components[0],
            &format!("{ctx}/het"),
        );
        assert_close(
            r.component_indices[1],
            case.components[1],
            &format!("{ctx}/loc"),
        );
        assert_close(
            r.component_indices[2],
            case.components[2],
            &format!("{ctx}/rou"),
        );
        assert_close(
            r.component_indices[3],
            case.components[3],
            &format!("{ctx}/sgn"),
        );
        assert_close(
            r.component_indices[4],
            case.components[4],
            &format!("{ctx}/tmp"),
        );
    }
}

#[test]
fn scenarios_small_grid() {
    let config = Config {
        grid_size: 41,
        time_steps: 41,
        ..Config::default()
    };
    let cases = [
        ScenarioOracle {
            scenario: Scenario::Calm,
            intensity: od::SC_SMALL_CALM_INTENSITY,
            structure: od::SC_SMALL_CALM_STRUCTURE,
            coupled: od::SC_SMALL_CALM_COUPLED,
            components: [
                od::SC_SMALL_CALM_HET,
                od::SC_SMALL_CALM_LOC,
                od::SC_SMALL_CALM_ROU,
                od::SC_SMALL_CALM_SGN,
                od::SC_SMALL_CALM_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Coherent,
            intensity: od::SC_SMALL_COHERENT_INTENSITY,
            structure: od::SC_SMALL_COHERENT_STRUCTURE,
            coupled: od::SC_SMALL_COHERENT_COUPLED,
            components: [
                od::SC_SMALL_COHERENT_HET,
                od::SC_SMALL_COHERENT_LOC,
                od::SC_SMALL_COHERENT_ROU,
                od::SC_SMALL_COHERENT_SGN,
                od::SC_SMALL_COHERENT_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Multi,
            intensity: od::SC_SMALL_MULTI_INTENSITY,
            structure: od::SC_SMALL_MULTI_STRUCTURE,
            coupled: od::SC_SMALL_MULTI_COUPLED,
            components: [
                od::SC_SMALL_MULTI_HET,
                od::SC_SMALL_MULTI_LOC,
                od::SC_SMALL_MULTI_ROU,
                od::SC_SMALL_MULTI_SGN,
                od::SC_SMALL_MULTI_TMP,
            ],
        },
    ];
    check_scenarios(&config, &cases, "small");

    // Sampled per-step series.
    let sim = SimConfig::default();
    let r = scirust_itd::simulate_canonical(Scenario::Coherent, &config, &sim).unwrap();
    for (k, &idx) in od::SC_SMALL_COHERENT_SAMPLE_IDX.iter().enumerate()
    {
        assert_close(
            r.intensity_rate[idx],
            od::SC_SMALL_COHERENT_SAMPLE_INTENSITY_RATE[k],
            "coherent/intensity_rate",
        );
        assert_close(
            r.heterogeneity[idx],
            od::SC_SMALL_COHERENT_SAMPLE_HET[k],
            "coherent/het",
        );
        assert_close(
            r.roughness[idx],
            od::SC_SMALL_COHERENT_SAMPLE_ROU[k],
            "coherent/rou",
        );
    }
    let r = scirust_itd::simulate_canonical(Scenario::Multi, &config, &sim).unwrap();
    for (k, &idx) in od::SC_SMALL_MULTI_SAMPLE_IDX.iter().enumerate()
    {
        assert_close(
            r.intensity_rate[idx],
            od::SC_SMALL_MULTI_SAMPLE_INTENSITY_RATE[k],
            "multi/intensity_rate",
        );
        assert_close(
            r.heterogeneity[idx],
            od::SC_SMALL_MULTI_SAMPLE_HET[k],
            "multi/het",
        );
        assert_close(
            r.roughness[idx],
            od::SC_SMALL_MULTI_SAMPLE_ROU[k],
            "multi/rou",
        );
    }
}

#[test]
fn scenarios_full_grid() {
    // The published configuration (161 x 161 grid, 401 steps).
    let config = Config::default();
    let cases = [
        ScenarioOracle {
            scenario: Scenario::Calm,
            intensity: od::SC_FULL_CALM_INTENSITY,
            structure: od::SC_FULL_CALM_STRUCTURE,
            coupled: od::SC_FULL_CALM_COUPLED,
            components: [
                od::SC_FULL_CALM_HET,
                od::SC_FULL_CALM_LOC,
                od::SC_FULL_CALM_ROU,
                od::SC_FULL_CALM_SGN,
                od::SC_FULL_CALM_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Coherent,
            intensity: od::SC_FULL_COHERENT_INTENSITY,
            structure: od::SC_FULL_COHERENT_STRUCTURE,
            coupled: od::SC_FULL_COHERENT_COUPLED,
            components: [
                od::SC_FULL_COHERENT_HET,
                od::SC_FULL_COHERENT_LOC,
                od::SC_FULL_COHERENT_ROU,
                od::SC_FULL_COHERENT_SGN,
                od::SC_FULL_COHERENT_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Multi,
            intensity: od::SC_FULL_MULTI_INTENSITY,
            structure: od::SC_FULL_MULTI_STRUCTURE,
            coupled: od::SC_FULL_MULTI_COUPLED,
            components: [
                od::SC_FULL_MULTI_HET,
                od::SC_FULL_MULTI_LOC,
                od::SC_FULL_MULTI_ROU,
                od::SC_FULL_MULTI_SGN,
                od::SC_FULL_MULTI_TMP,
            ],
        },
    ];
    check_scenarios(&config, &cases, "full");
}

// --- transport (semi-Lagrangian) ----------------------------------------

fn transport_velocity(x: f64, y: f64, t: f64) -> (f64, f64) {
    (
        0.4 * (x + 0.2 * t).cos() * y.sin(),
        -0.4 * x.sin() * (y - 0.1 * t).cos(),
    )
}

#[test]
fn transport_previous_vorticity_matches() {
    let tx = od::TX_COORDS.to_vec();
    let ty = od::TY_COORDS.to_vec();
    let prev = Field2::from_vec(od::TNY, od::TNX, od::TPREV.to_vec()).unwrap();

    let combos = [
        (
            Interpolation::BilinearPeriodic,
            Trajectory::MidpointTimeVelocity,
            od::T_BILINEAR_MIDPOINT,
            "bilinear/midpoint",
        ),
        (
            Interpolation::BilinearPeriodic,
            Trajectory::Rk4Backtrace,
            od::T_BILINEAR_RK4,
            "bilinear/rk4",
        ),
        (
            Interpolation::CubicPeriodic,
            Trajectory::MidpointTimeVelocity,
            od::T_CUBIC_MIDPOINT,
            "cubic/midpoint",
        ),
        (
            Interpolation::CubicPeriodic,
            Trajectory::Rk4Backtrace,
            od::T_CUBIC_RK4,
            "cubic/rk4",
        ),
    ];

    for (interp, traj, want, ctx) in combos
    {
        let got = transport_previous_vorticity(
            &prev,
            &tx,
            &ty,
            od::T_PREV_TIME,
            od::T_CUR_TIME,
            transport_velocity,
            interp,
            traj,
        )
        .unwrap();
        assert_slice_close(got.as_slice(), want, ctx);
    }
}

#[test]
fn transport_compensated_engine_matches() {
    let config = Config {
        grid_size: 41,
        time_steps: 41,
        ..Config::default()
    };
    let sim = SimConfig {
        boundary: BoundaryMode::Periodic,
        ..SimConfig::default()
    };

    let coherent = simulate_canonical_transport(
        Scenario::Coherent,
        &config,
        &sim,
        Interpolation::BilinearPeriodic,
        Trajectory::MidpointTimeVelocity,
    )
    .unwrap();
    assert_close(
        coherent.intensity_index,
        od::TC_COHERENT_INTENSITY,
        "tc/coherent/intensity",
    );
    assert_close(
        coherent.structure_index,
        od::TC_COHERENT_STRUCTURE,
        "tc/coherent/structure",
    );
    assert_close(
        coherent.coupled_index,
        od::TC_COHERENT_COUPLED,
        "tc/coherent/coupled",
    );
    assert_close(
        coherent.component_indices[4],
        od::TC_COHERENT_TMP,
        "tc/coherent/tmp",
    );
    assert_close(
        coherent.temporal_deformation_eulerian_index,
        od::TC_COHERENT_EUL_IDX,
        "tc/coherent/eul",
    );
    assert_close(
        coherent.temporal_deformation_compensated_index.unwrap(),
        od::TC_COHERENT_COMP_IDX,
        "tc/coherent/comp",
    );

    let multi = simulate_canonical_transport(
        Scenario::Multi,
        &config,
        &sim,
        Interpolation::CubicPeriodic,
        Trajectory::Rk4Backtrace,
    )
    .unwrap();
    assert_close(
        multi.intensity_index,
        od::TC_MULTI_INTENSITY,
        "tc/multi/intensity",
    );
    assert_close(
        multi.structure_index,
        od::TC_MULTI_STRUCTURE,
        "tc/multi/structure",
    );
    assert_close(
        multi.coupled_index,
        od::TC_MULTI_COUPLED,
        "tc/multi/coupled",
    );
    assert_close(multi.component_indices[4], od::TC_MULTI_TMP, "tc/multi/tmp");
    assert_close(
        multi.temporal_deformation_eulerian_index,
        od::TC_MULTI_EUL_IDX,
        "tc/multi/eul",
    );
    assert_close(
        multi.temporal_deformation_compensated_index.unwrap(),
        od::TC_MULTI_COMP_IDX,
        "tc/multi/comp",
    );
}

#[test]
fn transport_limiter_interpolations_match() {
    let tx = od::TX_COORDS.to_vec();
    let ty = od::TY_COORDS.to_vec();
    let sharp = Field2::from_vec(od::TNY, od::TNX, od::TPREV_SHARP.to_vec()).unwrap();
    let smooth = Field2::from_vec(od::TNY, od::TNX, od::TPREV.to_vec()).unwrap();

    let combos = [
        (
            Interpolation::CubicPeriodic,
            Trajectory::MidpointTimeVelocity,
            "cubic/mid",
        ),
        (
            Interpolation::CubicPeriodic,
            Trajectory::Rk4Backtrace,
            "cubic/rk4",
        ),
        (
            Interpolation::CubicLocalBoundedPeriodic,
            Trajectory::MidpointTimeVelocity,
            "bounded/mid",
        ),
        (
            Interpolation::CubicLocalBoundedPeriodic,
            Trajectory::Rk4Backtrace,
            "bounded/rk4",
        ),
        (
            Interpolation::CubicLocalSumPreservingPeriodic,
            Trajectory::MidpointTimeVelocity,
            "sumpres/mid",
        ),
        (
            Interpolation::CubicLocalSumPreservingPeriodic,
            Trajectory::Rk4Backtrace,
            "sumpres/rk4",
        ),
    ];
    let sharp_want: [&[f64]; 6] = [
        od::TL_SHARP_CUBIC_MIDPOINT,
        od::TL_SHARP_CUBIC_RK4,
        od::TL_SHARP_BOUNDED_MIDPOINT,
        od::TL_SHARP_BOUNDED_RK4,
        od::TL_SHARP_SUMPRES_MIDPOINT,
        od::TL_SHARP_SUMPRES_RK4,
    ];
    let smooth_want: [&[f64]; 6] = [
        od::TL_SMOOTH_CUBIC_MIDPOINT,
        od::TL_SMOOTH_CUBIC_RK4,
        od::TL_SMOOTH_BOUNDED_MIDPOINT,
        od::TL_SMOOTH_BOUNDED_RK4,
        od::TL_SMOOTH_SUMPRES_MIDPOINT,
        od::TL_SMOOTH_SUMPRES_RK4,
    ];

    for (k, (interp, traj, ctx)) in combos.iter().enumerate()
    {
        let r = transport_previous_vorticity(
            &sharp,
            &tx,
            &ty,
            od::T_PREV_TIME,
            od::T_CUR_TIME,
            transport_velocity,
            *interp,
            *traj,
        )
        .unwrap();
        assert_slice_close(r.as_slice(), sharp_want[k], &format!("sharp/{ctx}"));

        let r = transport_previous_vorticity(
            &smooth,
            &tx,
            &ty,
            od::T_PREV_TIME,
            od::T_CUR_TIME,
            transport_velocity,
            *interp,
            *traj,
        )
        .unwrap();
        assert_slice_close(r.as_slice(), smooth_want[k], &format!("smooth/{ctx}"));
    }

    // Property checks on the sharp field: the bounded limiter must actually
    // differ from the unlimited cubic (the limiter activated), and the
    // sum-preserving variant must reproduce the cubic's discrete sum.
    let sum = |s: &[f64]| s.iter().sum::<f64>();
    let cubic_sum = sum(od::TL_SHARP_CUBIC_MIDPOINT);
    let bounded_differs = od::TL_SHARP_BOUNDED_MIDPOINT
        .iter()
        .zip(od::TL_SHARP_CUBIC_MIDPOINT.iter())
        .any(|(a, b)| (a - b).abs() > 1e-6);
    assert!(
        bounded_differs,
        "the limiter must activate on the sharp field"
    );
    assert!(
        (sum(od::TL_SHARP_SUMPRES_MIDPOINT) - cubic_sum).abs() < 1e-9,
        "sum-preserving must reproduce the cubic discrete sum"
    );
}

// --- geometric transforms ------------------------------------------------

fn gt_field(flat: &[f64]) -> Field2 {
    Field2::from_vec(od::GT_NY, od::GT_NX, flat.to_vec()).unwrap()
}

#[test]
fn rotation_matrices_match() {
    for (k, &angle) in od::GT_ROT_ANGLES.iter().enumerate()
    {
        let q = Orthogonal2::rotation(angle).unwrap();
        let [[m00, m01], [m10, m11]] = q.as_array();
        let want: &[f64] = [od::GT_ROT_0, od::GT_ROT_1, od::GT_ROT_2, od::GT_ROT_3][k];
        assert_slice_close(&[m00, m01, m10, m11], want, &format!("rot[{k}]"));
        assert_close(q.determinant(), 1.0, &format!("rot[{k}]/det"));
        assert!(q.is_rotation(), "rot[{k}] should be a proper rotation");
    }
}

#[test]
fn transform_coordinates_match() {
    // Flattened (row-major) target grid coordinates: x = GTX[j], y = GTY[i].
    let mut xs = Vec::new();
    let mut ys = Vec::new();
    for i in 0..od::GT_NY
    {
        for j in 0..od::GT_NX
        {
            xs.push(od::GTX[j]);
            ys.push(od::GTY[i]);
        }
    }
    let q = Orthogonal2::rotation(od::GT_ANGLE).unwrap();
    let (sx, sy) = transform_coordinates(&xs, &ys, &q).unwrap();
    assert_slice_close(&sx, od::GT_COORD_SX, "coord/sx");
    assert_slice_close(&sy, od::GT_COORD_SY, "coord/sy");
}

#[test]
fn bilinear_transform_plan_generic() {
    let q = Orthogonal2::rotation(od::GT_ANGLE).unwrap();
    let origin = [od::GT_ORIGIN[0], od::GT_ORIGIN[1]];
    let plan = BilinearTransformPlan::new(od::GTX, od::GTY, q, origin, 0.0).unwrap();
    assert!(
        !plan.uses_exact_node_map(),
        "a generic rotation must not be node-aligned"
    );
    let scalar = plan.transform_scalar(&gt_field(od::GT_SCALAR)).unwrap();
    assert_slice_close(scalar.as_slice(), od::GT_T_SCALAR, "transform/scalar");

    let (tvx, tvy) = plan
        .transform_vector(&gt_field(od::GT_VX), &gt_field(od::GT_VY))
        .unwrap();
    assert_slice_close(tvx.as_slice(), od::GT_T_VX, "transform/vx");
    assert_slice_close(tvy.as_slice(), od::GT_T_VY, "transform/vy");
}

#[test]
fn bilinear_transform_plan_exact_node_map() {
    let q = Orthogonal2::rotation(std::f64::consts::FRAC_PI_2).unwrap();
    let plan = BilinearTransformPlan::new(od::GT_SQ, od::GT_SQ, q, [2.0, 2.0], 0.0).unwrap();
    assert!(
        plan.uses_exact_node_map(),
        "a 90-degree rotation about the centre of a square grid is node-aligned"
    );
    let sqf = Field2::from_vec(od::GT_SQ_N, od::GT_SQ_N, od::GT_SQF.to_vec()).unwrap();
    let rotated = plan.transform_scalar(&sqf).unwrap();
    assert_slice_close(rotated.as_slice(), od::GT_SQ_ROT90, "transform/sq_rot90");
}

// --- covariance (scaling + reference frames) ------------------------------

#[test]
fn spatial_scaling_matches() {
    let origin = [od::COV_ORIGIN[0], od::COV_ORIGIN[1]];
    let (sx, sy) = inverse_scale_coordinates(od::COV_X, od::COV_Y, od::COV_A, origin).unwrap();
    assert_slice_close(&sx, od::COV_INV_SX, "scale/inv_sx");
    assert_slice_close(&sy, od::COV_INV_SY, "scale/inv_sy");

    assert_close(
        scale_length(od::COV_LEN_IN, od::COV_A).unwrap(),
        od::COV_LEN_OUT,
        "scale/length",
    );

    let uniform = scale_geometry(&Geometry::uniform(0.5, 0.3).unwrap(), od::COV_A, origin).unwrap();
    match uniform
    {
        Geometry::Uniform { dx, dy } =>
        {
            assert_close(dx, od::COV_SCALED_DX, "scale/dx");
            assert_close(dy, od::COV_SCALED_DY, "scale/dy");
        },
        _ => panic!("expected a uniform geometry"),
    }

    let rect = scale_geometry(
        &Geometry::rectilinear(od::COV_X.to_vec(), od::COV_Y.to_vec()).unwrap(),
        od::COV_A,
        origin,
    )
    .unwrap();
    match rect
    {
        Geometry::Rectilinear { x, y } =>
        {
            assert_slice_close(&x, od::COV_SCALED_RX, "scale/rect_x");
            assert_slice_close(&y, od::COV_SCALED_RY, "scale/rect_y");
        },
        _ => panic!("expected a rectilinear geometry"),
    }
}

#[test]
fn reference_frames_match() {
    let c = [od::COV_C[0], od::COV_C[1]];
    let (gsx, gsy) =
        galilean_source_coordinates(od::COV_X, od::COV_Y, od::COV_T, c, od::COV_T0).unwrap();
    assert_slice_close(&gsx, od::COV_GAL_SX, "galilean/sx");
    assert_slice_close(&gsy, od::COV_GAL_SY, "galilean/sy");

    let b = [od::COV_B[0], od::COV_B[1]];
    let (tsx, tsy) = translating_frame_source_coordinates(od::COV_X, od::COV_Y, b).unwrap();
    assert_slice_close(&tsx, od::COV_TRANS_SX, "translating/sx");
    assert_slice_close(&tsy, od::COV_TRANS_SY, "translating/sy");
}

// --- multiscale profile ---------------------------------------------------

#[test]
fn multiscale_profile_matches() {
    let weights: [f64; 5] = od::MS_WEIGHTS.try_into().unwrap();
    let reference = MultiscaleReference {
        intensity_rate: od::MS_INTENSITY_RATE.to_vec(),
        heterogeneity: od::MS_HETEROGENEITY.to_vec(),
        localization: od::MS_LOCALIZATION.to_vec(),
        unit_roughness: od::MS_UNIT_ROUGHNESS.to_vec(),
        sign_mixing: od::MS_SIGN_MIXING.to_vec(),
        temporal_deformation_interval: od::MS_TDEF_INTERVAL.to_vec(),
        interval_dt: od::MS_INTERVAL_DT.to_vec(),
        weights,
        intensity_index: od::MS_INTENSITY_INDEX,
        temporal_deformation_index: od::MS_TDEF_INDEX,
    };
    let profile = derive_multiscale_profile(&reference, od::MS_LENGTHS).unwrap();

    let flat_signatures: Vec<f64> = profile.signatures.iter().flatten().copied().collect();
    assert_slice_close(&flat_signatures, od::MS_SIGNATURES, "ms/signatures");
    assert_slice_close(
        &profile.structure_indices,
        od::MS_STRUCTURE_IDX,
        "ms/structure",
    );
    assert_slice_close(&profile.coupled_indices, od::MS_COUPLED_IDX, "ms/coupled");
    assert_slice_close(
        &profile.raw_roughness_indices,
        od::MS_RAW_ROUGH_IDX,
        "ms/raw_roughness",
    );
    assert_close(
        profile.intensity_index,
        od::MS_INTENSITY_INDEX,
        "ms/intensity",
    );
    assert_close(
        profile.temporal_deformation_index,
        od::MS_TDEF_INDEX,
        "ms/tdef",
    );

    // The temporal-deformation signature component (index 4) is scale-independent.
    for k in 1..profile.signatures.len()
    {
        assert_close(
            profile.signatures[k][4],
            profile.signatures[0][4],
            "ms/tdef-scale-independent",
        );
    }
}

// --- material-derivative interval -----------------------------------------

fn mat_field(flat: &[f64]) -> Field2 {
    Field2::from_vec(od::MAT_NY, od::MAT_NX, flat.to_vec()).unwrap()
}

#[test]
fn material_interval_matches() {
    let geom = Geometry::uniform(od::MAT_DX, od::MAT_DY).unwrap();
    let res = material_vorticity_interval(
        &mat_field(od::MAT_PREV),
        &mat_field(od::MAT_CUR),
        &mat_field(od::MAT_VX),
        &mat_field(od::MAT_VY),
        &geom,
        od::MAT_DT,
        BoundaryMode::Finite,
    )
    .unwrap();

    assert_slice_close(
        res.temporal_tendency.as_slice(),
        od::MAT_TEMPORAL,
        "mat/temporal",
    );
    assert_slice_close(
        res.advective_tendency.as_slice(),
        od::MAT_ADVECTIVE,
        "mat/advective",
    );
    assert_slice_close(
        res.material_tendency.as_slice(),
        od::MAT_MATERIAL,
        "mat/material",
    );
    assert_close(res.reference_rms, od::MAT_REF_RMS, "mat/ref_rms");
    assert_close(res.previous_rms, od::MAT_PREV_RMS, "mat/prev_rms");
    assert_close(res.current_rms, od::MAT_CUR_RMS, "mat/cur_rms");
    assert_close(res.eulerian_rate, od::MAT_EUL_RATE, "mat/eul_rate");
    assert_close(res.advective_rate, od::MAT_ADV_RATE, "mat/adv_rate");
    assert_close(res.material_rate, od::MAT_MAT_RATE, "mat/mat_rate");
}

// --- material-deformation orchestration ------------------------------------

#[test]
fn material_deformation_orchestration_matches() {
    let config = Config {
        grid_size: 21,
        time_steps: 9,
        ..Config::default()
    };
    let sim = SimConfig::default();

    // Default advection: the scenario's own velocity field.
    let r = simulate_canonical_material(Scenario::Multi, &config, &sim).unwrap();
    assert_eq!(r.advection_source, AdvectionSource::VelocityField);
    assert_slice_close(
        &r.eulerian_rate_interval,
        od::MD_DEFAULT_EUL_IV,
        "md/default/eul_iv",
    );
    assert_slice_close(
        &r.advective_rate_interval,
        od::MD_DEFAULT_ADV_IV,
        "md/default/adv_iv",
    );
    assert_slice_close(
        &r.material_deformation_interval,
        od::MD_DEFAULT_MAT_IV,
        "md/default/mat_iv",
    );
    assert_slice_close(
        &r.eulerian_rate,
        od::MD_DEFAULT_EUL_NODAL,
        "md/default/eul_nodal",
    );
    assert_slice_close(
        &r.advective_rate,
        od::MD_DEFAULT_ADV_NODAL,
        "md/default/adv_nodal",
    );
    assert_slice_close(
        &r.material_deformation,
        od::MD_DEFAULT_MAT_NODAL,
        "md/default/mat_nodal",
    );
    assert_close(
        r.eulerian_rate_index,
        od::MD_DEFAULT_EUL_IDX,
        "md/default/eul_idx",
    );
    assert_close(
        r.advective_rate_index,
        od::MD_DEFAULT_ADV_IDX,
        "md/default/adv_idx",
    );
    assert_close(
        r.material_deformation_index,
        od::MD_DEFAULT_MAT_IDX,
        "md/default/mat_idx",
    );
    assert!(
        r.eulerian_consistency_error < 1e-12,
        "consistency {} not at machine-epsilon scale",
        r.eulerian_consistency_error
    );
    assert_close(
        r.baseline.intensity_index,
        od::MD_DEFAULT_BASE_INTENSITY,
        "md/default/base_intensity",
    );
    assert_close(
        r.baseline.structure_index,
        od::MD_DEFAULT_BASE_STRUCTURE,
        "md/default/base_structure",
    );

    // Separate advection field: the coherent flow advects the multi run.
    let xc = config.coordinates();
    let yc = xc.clone();
    let times = config.times();
    let geometry = Geometry::isotropic(config.spacing()).unwrap();
    let r = simulate_material_deformation_with_advection(
        "multi",
        |x, y, t| Scenario::Multi.velocity(x, y, t),
        curvature_field,
        |x, y, t| Scenario::Coherent.velocity(x, y, t),
        &xc,
        &yc,
        &times,
        &geometry,
        config.characteristic_length,
        &sim,
    )
    .unwrap();
    assert_eq!(r.advection_source, AdvectionSource::AdvectionVelocityField);
    assert_slice_close(
        &r.eulerian_rate_interval,
        od::MD_SEP_EUL_IV,
        "md/sep/eul_iv",
    );
    assert_slice_close(
        &r.advective_rate_interval,
        od::MD_SEP_ADV_IV,
        "md/sep/adv_iv",
    );
    assert_slice_close(
        &r.material_deformation_interval,
        od::MD_SEP_MAT_IV,
        "md/sep/mat_iv",
    );
    assert_slice_close(&r.eulerian_rate, od::MD_SEP_EUL_NODAL, "md/sep/eul_nodal");
    assert_slice_close(&r.advective_rate, od::MD_SEP_ADV_NODAL, "md/sep/adv_nodal");
    assert_slice_close(
        &r.material_deformation,
        od::MD_SEP_MAT_NODAL,
        "md/sep/mat_nodal",
    );
    assert_close(r.eulerian_rate_index, od::MD_SEP_EUL_IDX, "md/sep/eul_idx");
    assert_close(r.advective_rate_index, od::MD_SEP_ADV_IDX, "md/sep/adv_idx");
    assert_close(
        r.material_deformation_index,
        od::MD_SEP_MAT_IDX,
        "md/sep/mat_idx",
    );
    assert!(r.eulerian_consistency_error < 1e-12);
    assert_close(
        r.baseline.intensity_index,
        od::MD_SEP_BASE_INTENSITY,
        "md/sep/base_intensity",
    );
    assert_close(
        r.baseline.structure_index,
        od::MD_SEP_BASE_STRUCTURE,
        "md/sep/base_structure",
    );
}
