//! Validation of the Rust ITD port against reference (numpy) oracle values.
//!
//! The fixtures in `support/oracle_data.rs` were generated by running the
//! original ITD V29 engine and operators. Every value below is checked to a
//! tight tolerance; the analytic sanity checks (irrotational field ⇒ zero
//! intensity, rigid rotation ⇒ constant vorticity) are covered in the unit
//! tests inside the crate.

// Auto-generated numeric fixtures: some literals coincide with math constants
// (e.g. 1/√2), which is not a readability problem in generated data.
#[allow(dead_code, clippy::approx_constant)]
mod oracle_data {
    include!("support/oracle_data.rs");
}

use oracle_data as od;
use scirust_itd::operators::{bounded, gradient, spatial_mean, vorticity};
use scirust_itd::signature::{StructuralWeights, structural_metrics};
use scirust_itd::{
    BoundaryMode, Config, Field2, Geometry, Interpolation, Scenario, SimConfig, Trajectory,
    simulate_canonical_transport, transport_previous_vorticity,
};

const REL: f64 = 1e-9;
const ABS: f64 = 1e-11;

fn is_close(a: f64, b: f64) -> bool {
    (a - b).abs() <= ABS + REL * a.abs().max(b.abs())
}

#[track_caller]
fn assert_close(a: f64, b: f64, ctx: &str) {
    assert!(
        is_close(a, b),
        "{ctx}: got {a:.17e}, want {b:.17e}, diff {:.3e}",
        (a - b).abs()
    );
}

#[track_caller]
fn assert_slice_close(got: &[f64], want: &[f64], ctx: &str) {
    assert_eq!(got.len(), want.len(), "{ctx}: length mismatch");
    for (k, (&g, &w)) in got.iter().zip(want.iter()).enumerate()
    {
        assert_close(g, w, &format!("{ctx}[{k}]"));
    }
}

fn field(flat: &[f64]) -> Field2 {
    Field2::from_vec(od::NY, od::NX, flat.to_vec()).unwrap()
}

fn uniform() -> Geometry {
    Geometry::uniform(od::DX, od::DY).unwrap()
}

fn rectilinear() -> Geometry {
    Geometry::rectilinear(od::X_COORDS.to_vec(), od::Y_COORDS.to_vec()).unwrap()
}

// --- operators -----------------------------------------------------------

#[test]
fn gradient_uniform_finite() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &uniform(), BoundaryMode::Finite).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_UF_GY, "grad_uf_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_UF_GX, "grad_uf_gx");
}

#[test]
fn gradient_uniform_periodic() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &uniform(), BoundaryMode::Periodic).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_UP_GY, "grad_up_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_UP_GX, "grad_up_gx");
}

#[test]
fn gradient_rectilinear_finite() {
    let (gy, gx) = gradient(&field(od::FIELD_A), &rectilinear(), BoundaryMode::Finite).unwrap();
    assert_slice_close(gy.as_slice(), od::GRAD_RECT_GY, "grad_rect_gy");
    assert_slice_close(gx.as_slice(), od::GRAD_RECT_GX, "grad_rect_gx");
}

#[test]
fn vorticity_uniform_finite() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &uniform(), BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UF, "vort_uf");
}

#[test]
fn vorticity_uniform_finite_isotropic() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let geom = Geometry::isotropic(od::DX).unwrap();
    let w = vorticity(&vx, &vy, &geom, BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UF_ISO, "vort_uf_iso");
}

#[test]
fn vorticity_uniform_periodic() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &uniform(), BoundaryMode::Periodic).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_UP, "vort_up");
}

#[test]
fn vorticity_rectilinear_finite() {
    let vx = field(od::VX);
    let vy = field(od::VY);
    let w = vorticity(&vx, &vy, &rectilinear(), BoundaryMode::Finite).unwrap();
    assert_slice_close(w.as_slice(), od::VORT_RECT, "vort_rect");
}

#[test]
fn spatial_mean_matches() {
    let f = field(od::FIELD_A);
    assert_close(
        spatial_mean(&f, &uniform(), BoundaryMode::Finite).unwrap(),
        od::MEAN_UF,
        "mean_uf",
    );
    assert_close(
        spatial_mean(&f, &uniform(), BoundaryMode::Periodic).unwrap(),
        od::MEAN_UP,
        "mean_up",
    );
    assert_close(
        spatial_mean(&f, &rectilinear(), BoundaryMode::Finite).unwrap(),
        od::MEAN_RECT,
        "mean_rect",
    );
}

#[test]
fn bounded_matches() {
    for (&x, &want) in od::BOUNDED_IN.iter().zip(od::BOUNDED_OUT.iter())
    {
        assert_close(bounded(x), want, "bounded");
    }
}

#[test]
fn structural_metrics_matches() {
    let omega = field(od::FIELD_A);
    let prev = field(od::FIELD_B);
    let m = structural_metrics(
        &omega,
        &uniform(),
        Some(&prev),
        Some(od::SM_DT),
        od::SM_LEN,
        StructuralWeights::default(),
        BoundaryMode::Finite,
    )
    .unwrap();
    assert_close(m.heterogeneity, od::SM_HETEROGENEITY, "sm_het");
    assert_close(m.localization, od::SM_LOCALIZATION, "sm_loc");
    assert_close(m.roughness, od::SM_ROUGHNESS, "sm_rough");
    assert_close(m.sign_mixing, od::SM_SIGN_MIXING, "sm_sign");
    assert_close(
        m.temporal_deformation,
        od::SM_TEMPORAL_DEFORMATION,
        "sm_tdef",
    );
    assert_close(m.structure_score, od::SM_STRUCTURE_SCORE, "sm_score");
}

// --- scenarios -----------------------------------------------------------

struct ScenarioOracle {
    scenario: Scenario,
    intensity: f64,
    structure: f64,
    coupled: f64,
    components: [f64; 5],
}

fn check_scenarios(config: &Config, cases: &[ScenarioOracle], tag: &str) {
    let sim = SimConfig::default();
    for case in cases
    {
        let r = scirust_itd::simulate_canonical(case.scenario, config, &sim).unwrap();
        let ctx = format!("{tag}/{}", case.scenario.name());
        assert_close(
            r.intensity_index,
            case.intensity,
            &format!("{ctx}/intensity"),
        );
        assert_close(
            r.structure_index,
            case.structure,
            &format!("{ctx}/structure"),
        );
        assert_close(r.coupled_index, case.coupled, &format!("{ctx}/coupled"));
        assert_close(
            r.component_indices[0],
            case.components[0],
            &format!("{ctx}/het"),
        );
        assert_close(
            r.component_indices[1],
            case.components[1],
            &format!("{ctx}/loc"),
        );
        assert_close(
            r.component_indices[2],
            case.components[2],
            &format!("{ctx}/rou"),
        );
        assert_close(
            r.component_indices[3],
            case.components[3],
            &format!("{ctx}/sgn"),
        );
        assert_close(
            r.component_indices[4],
            case.components[4],
            &format!("{ctx}/tmp"),
        );
    }
}

#[test]
fn scenarios_small_grid() {
    let config = Config {
        grid_size: 41,
        time_steps: 41,
        ..Config::default()
    };
    let cases = [
        ScenarioOracle {
            scenario: Scenario::Calm,
            intensity: od::SC_SMALL_CALM_INTENSITY,
            structure: od::SC_SMALL_CALM_STRUCTURE,
            coupled: od::SC_SMALL_CALM_COUPLED,
            components: [
                od::SC_SMALL_CALM_HET,
                od::SC_SMALL_CALM_LOC,
                od::SC_SMALL_CALM_ROU,
                od::SC_SMALL_CALM_SGN,
                od::SC_SMALL_CALM_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Coherent,
            intensity: od::SC_SMALL_COHERENT_INTENSITY,
            structure: od::SC_SMALL_COHERENT_STRUCTURE,
            coupled: od::SC_SMALL_COHERENT_COUPLED,
            components: [
                od::SC_SMALL_COHERENT_HET,
                od::SC_SMALL_COHERENT_LOC,
                od::SC_SMALL_COHERENT_ROU,
                od::SC_SMALL_COHERENT_SGN,
                od::SC_SMALL_COHERENT_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Multi,
            intensity: od::SC_SMALL_MULTI_INTENSITY,
            structure: od::SC_SMALL_MULTI_STRUCTURE,
            coupled: od::SC_SMALL_MULTI_COUPLED,
            components: [
                od::SC_SMALL_MULTI_HET,
                od::SC_SMALL_MULTI_LOC,
                od::SC_SMALL_MULTI_ROU,
                od::SC_SMALL_MULTI_SGN,
                od::SC_SMALL_MULTI_TMP,
            ],
        },
    ];
    check_scenarios(&config, &cases, "small");

    // Sampled per-step series.
    let sim = SimConfig::default();
    let r = scirust_itd::simulate_canonical(Scenario::Coherent, &config, &sim).unwrap();
    for (k, &idx) in od::SC_SMALL_COHERENT_SAMPLE_IDX.iter().enumerate()
    {
        assert_close(
            r.intensity_rate[idx],
            od::SC_SMALL_COHERENT_SAMPLE_INTENSITY_RATE[k],
            "coherent/intensity_rate",
        );
        assert_close(
            r.heterogeneity[idx],
            od::SC_SMALL_COHERENT_SAMPLE_HET[k],
            "coherent/het",
        );
        assert_close(
            r.roughness[idx],
            od::SC_SMALL_COHERENT_SAMPLE_ROU[k],
            "coherent/rou",
        );
    }
    let r = scirust_itd::simulate_canonical(Scenario::Multi, &config, &sim).unwrap();
    for (k, &idx) in od::SC_SMALL_MULTI_SAMPLE_IDX.iter().enumerate()
    {
        assert_close(
            r.intensity_rate[idx],
            od::SC_SMALL_MULTI_SAMPLE_INTENSITY_RATE[k],
            "multi/intensity_rate",
        );
        assert_close(
            r.heterogeneity[idx],
            od::SC_SMALL_MULTI_SAMPLE_HET[k],
            "multi/het",
        );
        assert_close(
            r.roughness[idx],
            od::SC_SMALL_MULTI_SAMPLE_ROU[k],
            "multi/rou",
        );
    }
}

#[test]
fn scenarios_full_grid() {
    // The published configuration (161 x 161 grid, 401 steps).
    let config = Config::default();
    let cases = [
        ScenarioOracle {
            scenario: Scenario::Calm,
            intensity: od::SC_FULL_CALM_INTENSITY,
            structure: od::SC_FULL_CALM_STRUCTURE,
            coupled: od::SC_FULL_CALM_COUPLED,
            components: [
                od::SC_FULL_CALM_HET,
                od::SC_FULL_CALM_LOC,
                od::SC_FULL_CALM_ROU,
                od::SC_FULL_CALM_SGN,
                od::SC_FULL_CALM_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Coherent,
            intensity: od::SC_FULL_COHERENT_INTENSITY,
            structure: od::SC_FULL_COHERENT_STRUCTURE,
            coupled: od::SC_FULL_COHERENT_COUPLED,
            components: [
                od::SC_FULL_COHERENT_HET,
                od::SC_FULL_COHERENT_LOC,
                od::SC_FULL_COHERENT_ROU,
                od::SC_FULL_COHERENT_SGN,
                od::SC_FULL_COHERENT_TMP,
            ],
        },
        ScenarioOracle {
            scenario: Scenario::Multi,
            intensity: od::SC_FULL_MULTI_INTENSITY,
            structure: od::SC_FULL_MULTI_STRUCTURE,
            coupled: od::SC_FULL_MULTI_COUPLED,
            components: [
                od::SC_FULL_MULTI_HET,
                od::SC_FULL_MULTI_LOC,
                od::SC_FULL_MULTI_ROU,
                od::SC_FULL_MULTI_SGN,
                od::SC_FULL_MULTI_TMP,
            ],
        },
    ];
    check_scenarios(&config, &cases, "full");
}

// --- transport (semi-Lagrangian) ----------------------------------------

fn transport_velocity(x: f64, y: f64, t: f64) -> (f64, f64) {
    (
        0.4 * (x + 0.2 * t).cos() * y.sin(),
        -0.4 * x.sin() * (y - 0.1 * t).cos(),
    )
}

#[test]
fn transport_previous_vorticity_matches() {
    let tx = od::TX_COORDS.to_vec();
    let ty = od::TY_COORDS.to_vec();
    let prev = Field2::from_vec(od::TNY, od::TNX, od::TPREV.to_vec()).unwrap();

    let combos = [
        (
            Interpolation::BilinearPeriodic,
            Trajectory::MidpointTimeVelocity,
            od::T_BILINEAR_MIDPOINT,
            "bilinear/midpoint",
        ),
        (
            Interpolation::BilinearPeriodic,
            Trajectory::Rk4Backtrace,
            od::T_BILINEAR_RK4,
            "bilinear/rk4",
        ),
        (
            Interpolation::CubicPeriodic,
            Trajectory::MidpointTimeVelocity,
            od::T_CUBIC_MIDPOINT,
            "cubic/midpoint",
        ),
        (
            Interpolation::CubicPeriodic,
            Trajectory::Rk4Backtrace,
            od::T_CUBIC_RK4,
            "cubic/rk4",
        ),
    ];

    for (interp, traj, want, ctx) in combos
    {
        let got = transport_previous_vorticity(
            &prev,
            &tx,
            &ty,
            od::T_PREV_TIME,
            od::T_CUR_TIME,
            transport_velocity,
            interp,
            traj,
        )
        .unwrap();
        assert_slice_close(got.as_slice(), want, ctx);
    }
}

#[test]
fn transport_compensated_engine_matches() {
    let config = Config {
        grid_size: 41,
        time_steps: 41,
        ..Config::default()
    };
    let sim = SimConfig {
        boundary: BoundaryMode::Periodic,
        ..SimConfig::default()
    };

    let coherent = simulate_canonical_transport(
        Scenario::Coherent,
        &config,
        &sim,
        Interpolation::BilinearPeriodic,
        Trajectory::MidpointTimeVelocity,
    )
    .unwrap();
    assert_close(
        coherent.intensity_index,
        od::TC_COHERENT_INTENSITY,
        "tc/coherent/intensity",
    );
    assert_close(
        coherent.structure_index,
        od::TC_COHERENT_STRUCTURE,
        "tc/coherent/structure",
    );
    assert_close(
        coherent.coupled_index,
        od::TC_COHERENT_COUPLED,
        "tc/coherent/coupled",
    );
    assert_close(
        coherent.component_indices[4],
        od::TC_COHERENT_TMP,
        "tc/coherent/tmp",
    );
    assert_close(
        coherent.temporal_deformation_eulerian_index,
        od::TC_COHERENT_EUL_IDX,
        "tc/coherent/eul",
    );
    assert_close(
        coherent.temporal_deformation_compensated_index.unwrap(),
        od::TC_COHERENT_COMP_IDX,
        "tc/coherent/comp",
    );

    let multi = simulate_canonical_transport(
        Scenario::Multi,
        &config,
        &sim,
        Interpolation::CubicPeriodic,
        Trajectory::Rk4Backtrace,
    )
    .unwrap();
    assert_close(
        multi.intensity_index,
        od::TC_MULTI_INTENSITY,
        "tc/multi/intensity",
    );
    assert_close(
        multi.structure_index,
        od::TC_MULTI_STRUCTURE,
        "tc/multi/structure",
    );
    assert_close(
        multi.coupled_index,
        od::TC_MULTI_COUPLED,
        "tc/multi/coupled",
    );
    assert_close(multi.component_indices[4], od::TC_MULTI_TMP, "tc/multi/tmp");
    assert_close(
        multi.temporal_deformation_eulerian_index,
        od::TC_MULTI_EUL_IDX,
        "tc/multi/eul",
    );
    assert_close(
        multi.temporal_deformation_compensated_index.unwrap(),
        od::TC_MULTI_COMP_IDX,
        "tc/multi/comp",
    );
}
