// scirust-core/src/aot.rs
//! Ahead-of-time source generation for small static feed-forward models.
//!
//! The generator emits self-contained Rust source from an ordered layer list and a
//! little-endian `f32` parameter stream. Parameter bytes are decoded as `f32` values
//! and rendered into source with fixed decimal formatting. This textual representation
//! is not a bit-exact serialization of arbitrary IEEE-754 payloads. The generator does
//! not compile or execute the generated source, validate model quality, or provide a
//! versioned serialization format.

/// Layer kinds understood by the static source generator.
#[derive(Debug, Clone)]
pub enum LayerSpec {
    /// Dense affine layer `y = x W + b`.
    ///
    /// The parameter stream contains `in_features * out_features` row-major weights,
    /// followed immediately by `out_features` bias values, all encoded as little-endian
    /// IEEE-754 `f32` values.
    Linear {
        /// Number of input features consumed by the layer.
        in_features: usize,
        /// Number of output features produced by the layer.
        out_features: usize,
    },
    /// Element-wise rectified linear unit `max(x, 0)`.
    ReLU,
}

/// Generates Rust source for a fixed sequence of affine and ReLU layers.
///
/// `layers` is interpreted in order. For every [`LayerSpec::Linear`] layer,
/// `weights_bytes` must contain the layer's row-major weights followed by its bias
/// vector, with each value encoded as a little-endian `f32`. ReLU layers consume no
/// bytes. Under the current generator contract, `IN_DIM` is the `in_features` of the
/// first layer only when that first layer is linear; an empty sequence or a sequence
/// beginning with ReLU therefore declares `IN_DIM = 0`. `OUT_DIM` is updated to each
/// linear layer's `out_features` in sequence and therefore ends at the final linear
/// output width. Parameter values are rendered with eight digits after the decimal
/// point.
///
/// The function only generates source text; it does not invoke `rustc`, execute the
/// model, validate that adjacent linear layer dimensions are mutually compatible, or
/// guarantee bit-exact source round-tripping for every `f32` value. Trailing bytes after
/// the parameters required by `layers` are ignored.
///
/// # Panics
///
/// Panics when `weights_bytes` is shorter than the parameter stream declared by the
/// linear layers. Extremely large caller-supplied dimensions can also overflow the
/// intermediate byte-count arithmetic before slicing.
///
/// # Examples
///
/// ```
/// use scirust_core::aot::{generate_static_pipeline, LayerSpec};
///
/// // One 2 -> 1 affine layer: two row-major weights followed by one bias.
/// let mut parameters = Vec::new();
/// for value in [1.0_f32, -2.0, 0.5] {
///     parameters.extend_from_slice(&value.to_le_bytes());
/// }
///
/// let source = generate_static_pipeline(
///     &[
///         LayerSpec::Linear {
///             in_features: 2,
///             out_features: 1,
///         },
///         LayerSpec::ReLU,
///     ],
///     &parameters,
/// );
///
/// assert!(source.contains("pub const IN_DIM: usize = 2;"));
/// assert!(source.contains("pub const OUT_DIM: usize = 1;"));
/// assert!(source.contains("let mut acc = self.bias_0[o];"));
/// ```
///
/// An empty layer sequence consumes no parameters and generates a zero-dimensional
/// identity-shaped model skeleton:
///
/// ```
/// use scirust_core::aot::generate_static_pipeline;
///
/// let source = generate_static_pipeline(&[], &[]);
/// assert!(source.contains("pub const IN_DIM: usize = 0;"));
/// assert!(source.contains("pub const OUT_DIM: usize = 0;"));
/// ```
pub fn generate_static_pipeline(layers: &[LayerSpec], weights_bytes: &[u8]) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by SciRust AOT Compiler\n\n");

    // Find input and output dimensions
    let in_dim = if let Some(LayerSpec::Linear { in_features, .. }) = layers.first()
    {
        *in_features
    }
    else
    {
        0
    };

    let mut out_dim = in_dim;
    for layer in layers
    {
        if let LayerSpec::Linear { out_features, .. } = layer
        {
            out_dim = *out_features;
        }
    }

    code.push_str(&format!("pub const IN_DIM: usize = {};\n", in_dim));
    code.push_str(&format!("pub const OUT_DIM: usize = {};\n\n", out_dim));

    code.push_str("pub struct StaticModel {\n");

    let mut current_offset = 0;
    let mut weight_arrays = Vec::new();
    let mut bias_arrays = Vec::new();

    for (i, layer) in layers.iter().enumerate()
    {
        if let LayerSpec::Linear {
            in_features,
            out_features,
        } = layer
        {
            let size = in_features * out_features;
            let end = current_offset + size * 4;
            let weights_slice = &weights_bytes[current_offset..end];
            let mut f32_weights = Vec::new();
            for chunk in weights_slice.as_chunks::<4>().0
            {
                f32_weights.push(f32::from_le_bytes(*chunk));
            }

            // A Linear layer is `y = x·W + b`; the `out_features` bias values
            // follow the weight matrix in the byte stream. Omitting them (as the
            // generated code previously did) makes every compiled Linear layer
            // numerically wrong for any real trained model.
            let bias_end = end + out_features * 4;
            let bias_slice = &weights_bytes[end..bias_end];
            let mut f32_bias = Vec::new();
            for chunk in bias_slice.as_chunks::<4>().0
            {
                f32_bias.push(f32::from_le_bytes(*chunk));
            }

            code.push_str(&format!(
                "    pub weight_{}: [[f32; {}]; {}],\n",
                i, out_features, in_features
            ));
            code.push_str(&format!("    pub bias_{}: [f32; {}],\n", i, out_features));

            let mut val_str = String::new();
            val_str.push_str("[\n");
            for row in 0..*in_features
            {
                val_str.push_str("            [");
                for col in 0..*out_features
                {
                    val_str.push_str(&format!("{:.8}, ", f32_weights[row * out_features + col]));
                }
                val_str.push_str("],\n");
            }
            val_str.push_str("        ]");
            weight_arrays.push((i, val_str));

            let mut bias_str = String::from("[");
            for b in &f32_bias
            {
                bias_str.push_str(&format!("{:.8}, ", b));
            }
            bias_str.push(']');
            bias_arrays.push((i, bias_str));

            current_offset = bias_end;
        }
    }
    code.push_str("}\n\n");

    code.push_str("impl StaticModel {\n");
    code.push_str("    pub const fn new() -> Self {\n");
    code.push_str("        Self {\n");
    for (i, val) in &weight_arrays
    {
        code.push_str(&format!("            weight_{}: {},\n", i, val));
        let bias = &bias_arrays
            .iter()
            .find(|(bi, _)| bi == i)
            .expect("every weight has a matching bias")
            .1;
        code.push_str(&format!("            bias_{}: {},\n", i, bias));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn forward<const B: usize>(&self, input: &[[f32; IN_DIM]; B]) -> [[f32; OUT_DIM]; B] {\n");

    let mut current_dim = in_dim;
    let mut buffer_idx = 0;
    code.push_str("        let mut buf0 = *input;\n");

    for (i, layer) in layers.iter().enumerate()
    {
        match layer
        {
            LayerSpec::Linear {
                in_features,
                out_features,
            } =>
            {
                let next_buffer_idx = buffer_idx + 1;
                code.push_str(&format!(
                    "        let mut buf{} = [[0.0f32; {}]; B];\n",
                    next_buffer_idx, out_features
                ));
                code.push_str("        for b in 0..B {\n");
                code.push_str(&format!("            for o in 0..{} {{\n", out_features));
                code.push_str(&format!(
                    "                let mut acc = self.bias_{}[o];\n",
                    i
                ));
                code.push_str(&format!("                for i in 0..{} {{\n", in_features));
                code.push_str(&format!(
                    "                    acc += buf{}[b][i] * self.weight_{}[i][o];\n",
                    buffer_idx, i
                ));
                code.push_str("                }\n");
                code.push_str(&format!(
                    "                buf{}[b][o] = acc;\n",
                    next_buffer_idx
                ));
                code.push_str("            }\n");
                code.push_str("        }\n");
                buffer_idx = next_buffer_idx;
                current_dim = *out_features;
            },
            LayerSpec::ReLU =>
            {
                code.push_str("        for b in 0..B {\n");
                code.push_str(&format!("            for d in 0..{} {{\n", current_dim));
                code.push_str(&format!(
                    "                if buf{}[b][d] < 0.0 {{ buf{}[b][d] = 0.0; }}\n",
                    buffer_idx, buffer_idx
                ));
                code.push_str("            }\n");
                code.push_str("        }\n");
            },
        }
    }

    code.push_str(&format!("        buf{}\n", buffer_idx));
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}
