// scirust-core/src/aot.rs
// Ahead-Of-Time (AOT) Static Model Compiler for SciRust

#[derive(Debug, Clone)]
pub enum LayerSpec {
    Linear { in_features: usize, out_features: usize },
    ReLU,
}

pub fn generate_static_pipeline(layers: &[LayerSpec], weights_bytes: &[u8]) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by SciRust AOT Compiler\n\n");

    // Find input and output dimensions
    let in_dim = if let Some(LayerSpec::Linear { in_features, .. }) = layers.first() {
        *in_features
    } else {
        0
    };

    let mut out_dim = in_dim;
    for layer in layers {
        if let LayerSpec::Linear { out_features, .. } = layer {
            out_dim = *out_features;
        }
    }

    code.push_str(&format!("pub const IN_DIM: usize = {};\n", in_dim));
    code.push_str(&format!("pub const OUT_DIM: usize = {};\n\n", out_dim));

    code.push_str("pub struct StaticModel {\n");

    let mut current_offset = 0;
    let mut weight_arrays = Vec::new();

    for (i, layer) in layers.iter().enumerate() {
        if let LayerSpec::Linear { in_features, out_features } = layer {
            let size = in_features * out_features;
            let end = current_offset + size * 4;
            let weights_slice = &weights_bytes[current_offset..end];
            let mut f32_weights = Vec::new();
            for chunk in weights_slice.chunks_exact(4) {
                f32_weights.push(f32::from_le_bytes(chunk.try_into().unwrap()));
            }

            code.push_str(&format!("    pub weight_{}: [[f32; {}]; {}],\n", i, out_features, in_features));

            let mut val_str = String::new();
            val_str.push_str("[\n");
            for row in 0..*in_features {
                val_str.push_str("            [");
                for col in 0..*out_features {
                    val_str.push_str(&format!("{:.8}, ", f32_weights[row * out_features + col]));
                }
                val_str.push_str("],\n");
            }
            val_str.push_str("        ]");
            weight_arrays.push((i, val_str));

            current_offset = end;
        }
    }
    code.push_str("}\n\n");

    code.push_str("impl StaticModel {\n");
    code.push_str("    pub const fn new() -> Self {\n");
    code.push_str("        Self {\n");
    for (i, val) in &weight_arrays {
        code.push_str(&format!("            weight_{}: {},\n", i, val));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn forward<const B: usize>(&self, input: &[[f32; IN_DIM]; B]) -> [[f32; OUT_DIM]; B] {\n");

    let mut current_dim = in_dim;
    let mut buffer_idx = 0;
    code.push_str(&format!("        let mut buf0 = *input;\n"));

    for (i, layer) in layers.iter().enumerate() {
        match layer {
            LayerSpec::Linear { in_features, out_features } => {
                let next_buffer_idx = buffer_idx + 1;
                code.push_str(&format!("        let mut buf{} = [[0.0f32; {}]; B];\n", next_buffer_idx, out_features));
                code.push_str(&format!("        for b in 0..B {{\n"));
                code.push_str(&format!("            for o in 0..{} {{\n", out_features));
                code.push_str(&format!("                let mut acc = 0.0f32;\n"));
                code.push_str(&format!("                for i in 0..{} {{\n", in_features));
                code.push_str(&format!("                    acc += buf{}[b][i] * self.weight_{}[i][o];\n", buffer_idx, i));
                code.push_str("                }\n");
                code.push_str(&format!("                buf{}[b][o] = acc;\n", next_buffer_idx));
                code.push_str("            }\n");
                code.push_str("        }\n");
                buffer_idx = next_buffer_idx;
                current_dim = *out_features;
            }
            LayerSpec::ReLU => {
                code.push_str(&format!("        for b in 0..B {{\n"));
                code.push_str(&format!("            for d in 0..{} {{\n", current_dim));
                code.push_str(&format!("                if buf{}[b][d] < 0.0 {{ buf{}[b][d] = 0.0; }}\n", buffer_idx, buffer_idx));
                code.push_str("            }\n");
                code.push_str("        }\n");
            }
        }
    }

    code.push_str(&format!("        buf{}\n", buffer_idx));
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}
