//! Phase 5C.1 walkthrough: wraps the crate's existing (PR #810) causal
//! discovery pipeline in the typed contract layer — variables, dataset,
//! assumption registry, graph constraints, and a certificate — and shows the
//! one rule the certificate enforces: **a non-identified claim cannot carry a
//! numeric estimate.**
//!
//! This program produces no new causal knowledge. It runs the existing
//! optimizer on synthetic data from a *known* generating chain, and reports
//! the result as `EquivalenceClassOnly`, not `Identifiable` — because nothing
//! in this crate performs the identifiability reasoning that would justify a
//! stronger claim. Run twice, its printed fingerprints are identical.

use scirust_causal::{
    AssumptionBasis, AssumptionRegistry, CausalAssumption, CausalCertificate, CausalDataset,
    CausalVariable, Environment, GraphConstraints, IdentifiabilityStatus, OptimizerConfig,
    SyntheticDataConfig, TriangularCubicFlow, VariableKind, VariableRole, extract_causal_dag,
    generate_causal_samples, optimize_causal,
};

fn main() {
    // 1. A known synthetic chain X0 -> X1 -> X2 (A[1,0] = 0.5, A[2,1] = 0.3),
    //    exactly as in the crate's end-to-end tests.
    let true_weights = vec![0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.3, 0.0];
    let flow = TriangularCubicFlow::from_row_major(3, true_weights).unwrap();
    let synth_config = SyntheticDataConfig::new(2026, 3, 20).unwrap();
    let samples = generate_causal_samples(&flow, &synth_config).unwrap();

    // 2. Typed variables. Roles reflect this specific query ("what causes
    //    X2?"), not an intrinsic property of the variables.
    let variables = vec![
        CausalVariable::new(0, "x0", VariableRole::Treatment, VariableKind::Continuous).unwrap(),
        CausalVariable::new(1, "x1", VariableRole::Mediator, VariableKind::Continuous).unwrap(),
        CausalVariable::new(2, "x2", VariableRole::Outcome, VariableKind::Continuous).unwrap(),
    ];

    // 3. A provenance-carrying dataset: one purely observational environment.
    let environment = Environment::observational("synthetic_seed_2026").unwrap();
    let dataset = CausalDataset::single_environment(
        variables,
        environment,
        &samples,
        "synthetic: TriangularCubicFlow chain X0->X1->X2, seed=2026, n=20",
    )
    .unwrap();
    println!(
        "dataset: {} variables, {} samples across {} environment(s), purely observational = {}",
        dataset.variables.len(),
        dataset.total_samples(),
        dataset.blocks.len(),
        dataset.is_purely_observational()
    );

    // 4. Assumption registry: honest provenance, not a wishlist. This is
    //    synthetic data from a strictly-triangular cubic flow, so acyclicity
    //    and the functional form are true by construction (`GuaranteedByDesign`).
    //    Causal sufficiency and faithfulness are NOT checked by anything in
    //    this crate, so they stay `Unverified` — the honest default.
    let mut assumptions = AssumptionRegistry::new();
    assumptions
        .assert(
            CausalAssumption::Acyclicity,
            AssumptionBasis::GuaranteedByDesign {
                mechanism: "TriangularCubicFlow is strictly lower triangular by construction"
                    .to_string(),
            },
            None,
        )
        .unwrap();
    assumptions
        .assert(
            CausalAssumption::CorrectFunctionalForm,
            AssumptionBasis::GuaranteedByDesign {
                mechanism: "samples are generated by the exact cubic flow the score assumes"
                    .to_string(),
            },
            None,
        )
        .unwrap();
    assumptions
        .assert(
            CausalAssumption::CausalSufficiency,
            AssumptionBasis::Unverified,
            None,
        )
        .unwrap();
    assumptions
        .assert(
            CausalAssumption::AdequateSampleSize,
            AssumptionBasis::Unverified,
            Some(
                "n=20 for a 3-variable cubic model; not checked against any power analysis"
                    .to_string(),
            ),
        )
        .unwrap();
    println!("\nassumption registry ({} entries):", assumptions.len());
    for (assumption, record) in assumptions.iter()
    {
        println!("  {assumption:?}: {:?}", record.basis);
    }

    // 5. Background knowledge: a temporal ordering (X0 before X1 before X2)
    //    is often known even when the edges themselves are not.
    let mut constraints = GraphConstraints::new(3);
    constraints.set_tier(0, 0).unwrap();
    constraints.set_tier(1, 1).unwrap();
    constraints.set_tier(2, 2).unwrap();

    // 6. Run the EXISTING (unmodified) discovery pipeline off the zero saddle.
    let initial = scirust_solvers::Matrix::from_row_major(
        3,
        3,
        vec![0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.05, 0.05, 0.0],
    );
    let opt_config = OptimizerConfig::new(100, 20, 1.0e-5, 1.0e-10).unwrap();
    let result = optimize_causal(
        &dataset.blocks[0].to_matrix(),
        &initial,
        0.01,
        1.0e-8,
        0.0,
        1.0,
        &opt_config,
    )
    .unwrap();
    let graph_config = scirust_causal::GraphExtractionConfig::new(0.1).unwrap();
    let dag = extract_causal_dag(&result.interactions, &graph_config).unwrap();

    let violations = constraints.check(&dag);
    println!(
        "\ndiscovery: termination={:?}, extracted graph respects the declared tiers = {}",
        result.termination,
        violations.is_empty()
    );

    // 7. The certificate. Discovery found A graph, not necessarily THE graph —
    //    see the crate root's "Causal interpretation" section. Reporting
    //    anything better than `EquivalenceClassOnly` here would be exactly the
    //    unjustified causal claim this whole layer exists to prevent.
    let used: Vec<CausalAssumption> = assumptions.iter().map(|(a, _)| a.clone()).collect();
    let certificate = CausalCertificate::builder(
        "which variables directly cause x2?",
        IdentifiabilityStatus::EquivalenceClassOnly,
        used,
        format!(
            "{} observational samples, single environment, source: {}",
            dataset.total_samples(),
            dataset.source
        ),
    )
    .with_unresolved_alternative("reverse edge orientation within the discovered skeleton")
    .with_unresolved_alternative(
        "an unmeasured confounder of x1 and x2 (causal sufficiency unverified)",
    )
    .finalize()
    .unwrap();

    println!("\ncertificate:");
    println!("  query: {}", certificate.query());
    println!("  status: {:?}", certificate.status());
    println!(
        "  estimate: {:?} (none — status is not Identifiable)",
        certificate.estimate()
    );
    println!(
        "  unresolved alternatives: {:?}",
        certificate.unresolved_alternatives()
    );
    println!("  fingerprint: {}", certificate.fingerprint());

    // 8. Demonstrate the coherence rule directly: attaching a numeric
    //    estimate to a non-Identifiable status is a construction error, not a
    //    value the type will silently hold.
    let rejected = CausalCertificate::builder(
        "which variables directly cause x2?",
        IdentifiabilityStatus::EquivalenceClassOnly,
        vec![],
        "same evidence",
    )
    .with_estimate("would-be point estimate", 0.42, 0.01)
    .finalize();
    println!(
        "\nattaching an estimate to a non-Identifiable certificate: {:?}",
        rejected.unwrap_err()
    );

    // 9. JSON round trip, byte-exact on the embedded f64 sample data.
    let dataset_json = serde_json::to_string(&dataset).unwrap();
    let dataset_back: CausalDataset = serde_json::from_str(&dataset_json).unwrap();
    assert_eq!(dataset, dataset_back);
    let cert_json = serde_json::to_string(&certificate).unwrap();
    let cert_back: CausalCertificate = serde_json::from_str(&cert_json).unwrap();
    assert_eq!(certificate, cert_back);
    println!(
        "\nJSON round trip verified: dataset ({} bytes) and certificate ({} bytes) both bit-exact",
        dataset_json.len(),
        cert_json.len()
    );
}
